### ISSUE TITLE
大佬按照博客教程装好后应该怎么操作

### ISSUE THREAD

**Issue by yl948** [kukume/tgbot#1]
Tg机器人那边没有哪些功能
![Uploading f4aecfdecb5fcd980d38d989ef4a02dd.png…]()

**Comment by yl948** [comment]
现在可以用了输入/命令可以不知道大佬的菜单是如何调用出来的

**Comment by kukume** [comment]
https://www.kuku.me/archives/40/
已更新在指令一栏

**Comment by yl948** [comment]
感谢大佬更新

kuku ***@***.***>于2023年7月3日 周一13:06写道：
