### ISSUE TITLE
自建部署安装mongodb版本可选

### ISSUE THREAD

**Issue by jaxMineKa** [kukume/tgbot#13]
你好请问下mongodb版本最高适配哪一个？我看你写的Dockerfile是用mongo4，但是我在官网下载4.4.26选择没有22.04.3 LTS Jammy，系统最高支持ubuntu 20，也试过下载运行会缺失一堆库。

官网下载：https://www.mongodb.com/try/download/community
安装文旦说是支持ubuntu Jammy： https://www.mongodb.com/docs/v4.4/tutorial/install-mongodb-on-ubuntu-tarball/

**Comment by kukume** [comment]
支持最新版本的
默认选择4是因为我的设备的cpu不支持最新版本，好像是缺少一个指令。

**Comment by jaxMineKa** [comment]
> 支持最新版本的 默认选择4是因为我的设备的cpu不支持最新版本，好像是缺少一个指令。

非常感谢，7.0版本可以运行
