### ISSUE TITLE
大哥，能不能搞个视频讲一下怎么弄。

### ISSUE THREAD

**Issue by chinahaoba** [kukume/tgbot#14]
小白有需求，不会搞。能不能搞个视频讲一下

**Comment by kukume** [comment]
如何搭建的视频？

**Comment by chinahaoba** [comment]
> 如何搭建视频？

对呀。就是讲一下怎么搞

**Comment by wfby2068** [comment]
机器人已经激活，start后有反馈，但是继续点击选项没有反馈，无论是哪个选项，求解……

**Comment by kukume** [comment]
@wfby2068 另外开一个issues写详细一点，没看懂你的，如果没有反馈一般是报错了，最好提供日志

**Comment by kukume** [comment]
https://pan.kuku.me/tgbot/video
