### ISSUE TITLE
[建议] 增加linux.do论坛自动访问

### ISSUE THREAD

**Issue by endercatone** [kukume/tgbot#18]
[建议] 增加linux.do论坛自动访问和自动看帖子
也是一个比较热门的论坛(・∀・)

**Comment by kukume** [comment]
能给个邀请吗？我没有账号测试。

**Comment by endercatone** [comment]
> 能给个邀请吗？我没有账号测试。

https://linux.do/invites/PksrLeoPfC

十分感谢(. ❛ ᴗ ❛.)

**Comment by kukume** [comment]
我好像没有看到浏览帖子有什么奖励。
具体需求是每天访问一下主页和随机访问几个帖子吗？

**Comment by endercatone** [comment]
对的，刷访问天数
访问帖子可以选择性加入，刷已读帖子数（在总结处可以看到，用于等级升级）（帖子下面回帖的也算一个帖子(・∀・)）

**Comment by kukume** [comment]
目前策略，3个小时访问一次帖子，每天访问一次主页。暂时只能抓cookie，不能模拟登陆。

**Comment by kukume** [comment]
已支持模拟登陆。
