### ISSUE TITLE
nodeseek登录一直显示请稍后

### ISSUE THREAD

**Issue by chaoticjoy** [kukume/tgbot#2]
docker部署，添加账号，nodeseek，用户名密码登录，登录一直显示请稍后。cookie登录没有问题。

**Comment by kukume** [comment]
无头浏览器（依赖太大，且性能占用高，均请求我的api完成）未通过recaptchaV3，自动转成了recaptchaV2（推测可能是ip问题），对接了一个打码网站来过recaptchaV2，耗时很长，最慢1分钟。
建议通过cookie登陆
