### ISSUE TITLE
NodeSeek签到失败，未获取到NodeSeek签到执行结果

### ISSUE THREAD

**Issue by liuvps** [kukume/tgbot#23]
最近一周不行了

**Comment by kukume** [comment]
重新抓一下cookie，把抓到的一个请求的所有cookie提交，应该就没问题了

**Comment by liuvps** [comment]
> 重新抓一下cookie，把抓到的一个请求的所有cookie提交，应该就没问题了

啊，有示例吗？怎么操作？

**Comment by kukume** [comment]
不会抓cookie吗？浏览器开F12，或者右键打开检查，然后打开nodeseek（已登录状态），在网络那栏，随便找个域名是nodeseek的并且有cookie的，把cookie后面的内容复制下来，然后在机器人里面使用cookie绑定

**Comment by liuvps** [comment]
> 不会抓cookie吗？浏览器开F12，或者右键打开检查，然后打开nodeseek（已登录状态），在网络那栏，随便找个域名是nodeseek的并且有cookie的，把cookie后面的内容复制下来，然后在机器人里面使用cookie绑定

会抓cookie，是直接session=那一大串cookie值？不能单独等于session了是吧？

**Comment by kukume** [comment]
对的，只有session会跳验证码，全部带上不会跳验证码

**Comment by liuvps** [comment]
了解，等有空试一下，3Q
