### ISSUE TITLE
hostloc账号密码登录失败

### ISSUE THREAD

**Issue by Nodewebzsz** [kukume/tgbot#25]
at me.kuku.telegram.logic.HostLocLogic.login(HostLocLogic.kt:22) ~[!/:1.0-SNAPSHOT]
tgbot          |        at me.kuku.telegram.logic.HostLocLogic$login$1.invokeSuspend(HostLocLogic.kt) ~[!/:1.0-SNAPSHOT]
tgbot          |        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-2.0.0.jar!/:2.0.0-release-341]
tgbot          |        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[kotlinx-coroutines-core-jvm-1.7.3.jar!/:na]
tgbot          |        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[kotlinx-coroutines-core-jvm-1.7.3.jar!/:na]
tgbot          |        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) ~[kotlinx-coroutines-core-jvm-1.7.3.jar!/:na]
tgbot          |        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) ~[kotlinx-coroutines-core-jvm-1.7.3.jar!/:na]
tgbot          |        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) ~[kotlinx-coroutines-core-jvm-1.7.3.jar!/:na]
tgbot          | 
tgbot          | 2024-06-07T13:52:59.819+08:00  INFO 8 --- [pGroupProxy-5-1] ktor.application                         : 404 Not Found: GET - / in 1ms
tgbot          | 2024-06-07T13:53:00.871+08:00  INFO 8 --- [pGroupProxy-5-2] ktor.application                         : 404 Not Found: GET - / in 1ms
tgbot          | 2024-06-07T13:53:02.691+08:00  INFO 8 --- [pGroupProxy-5-1] ktor.application                         : 404 Not Found: GET - / in 0ms
tgbot          | 2024-06-07T13:53:03.962+08:00  INFO 8 --- [pGroupProxy-5-2] ktor.application                         : 404 Not Found: GET - / in 1ms
tgbot          | 2024-06-07T13:54:56.451+08:00 ERROR 8 --- [               ] m.k.t.context.TelegramExceptionHandler   : Unexpected error occurred in telegram subscribe
tgbot          | 
tgbot          | java.lang.IllegalStateException: 账号或密码错误或其他原因登录失败！

**Comment by kukume** [comment]
白天尝试了一下和你一样的，现在测试没有问题了，你再试试。
另外新增了抓包cookie绑定hostloc

**Comment by Nodewebzsz** [comment]
今天发现自动签到也挂了：
#自动签到失败提醒
NodeSeek执行失败，Socket timeout has expired [url=https://api.jpa.cc/nodeseek/sign/query?cookie=colorscheme%3Ddark%3B+, socket_timeout=unknown] ms


#手动执行结果
NodeSeek签到失败，Expected response body of the type 'class com.fasterxml.jackson.databind.JsonNode' but was 'class io.ktor.utils.io.ByteBufferChannel'
In response from `https://api.jpa.cc/nodeseek/sign/query?cookie=colorscheme%3Ddark%3B+.C4Hw%3B`

**Comment by kukume** [comment]
用无头浏览器实现的，可能量太大，服务器被卡死了。在考虑怎么解决。

**Comment by Nodewebzsz** [comment]
大佬，有私聊方式吗，有些这个项目的问题想请教下

**Comment by kukume** [comment]
可以新开issues。
另外使用无头浏览器的api加了同步。重新上线了。

**Comment by Nodewebzsz** [comment]
请问大佬，这个dockerfile可以构建自己镜像么，如何对接使用自己的mysql数据库啊

**Comment by kukume** [comment]
不支持mysql。因为我用的是mongodb，是非关系型数据库。
如果我用的是关系型数据库就支持。

mysql等要自己建表，选类型，很麻烦，所以我选择了mongo，它不需要建表什么的。

**Comment by Nodewebzsz** [comment]
好的，那么我要如何在navicat数据库工具连接数据库查看数据呢，大佬

**Comment by kukume** [comment]
docker的配置文件
```
mongo:
    image: mongo:4
    volumes:
      - ./db:/data/db
      - ./dump:/dump
```
改成
```
mongo:
    image: mongo:4
    ports: 
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./dump:/dump
```
新建链接，mongodb，ip，端口27017，用户名密码都是空。
如果需要新增用户名和密码，可以查看一下文档。

**Comment by Nodewebzsz** [comment]
ok,感谢大佬

**Comment by Nodewebzsz** [comment]
OK
