### ISSUE TITLE
大佬可以重新弄个部署教程吗？

### ISSUE THREAD

**Issue by lostme01** [kukume/tgbot#3]
大佬可以重新弄个部署教程吗？我想用阿里云盘功能，可是我部署了，机器人是有反应的，但是阿里云盘任务好像没有成功

**Comment by lostme01** [comment]
我是选择了手动运行，等了半天任务没完成，还有就是阿里云盘进去提示输入日期，也不知道格式是什么样子

**Comment by kukume** [comment]
做任务的话，写了延迟，时间会很长，没有返回结果。
领取是领取第几日的奖励，一个月的1-30日。

**Comment by lostme01** [comment]
我再试试，谢谢
