### ISSUE TITLE
继续反馈问题

### ISSUE THREAD

**Issue by lostme01** [kukume/tgbot#6]
#手动执行结果：
阿里云盘完成任务失败，失败原因：TooManyRequests

手动运行阿里云盘任务

**Comment by lostme01** [comment]
有其他联系方式吗？比如tg群之类的

**Comment by lostme01** [comment]
这个提示好像是任务已经完成了？

**Comment by kukume** [comment]
一天只可以接三次，接三次以上就会提示这个。
完成了的。
联系方式  @kukume
