### ISSUE TITLE
自建

### ISSUE THREAD

**Issue by dudt** [kukume/tgbot#7]
大佬自建在本地机器了，使用阿里云盘扫码登陆显示的还是你提供的广州登陆的啊？不应该在本地执行登陆嘛？

**Comment by kukume** [comment]
以前写过在线拿token的网页，偷懒直接调用接口了

**Comment by kukume** [comment]
fe19ccf
登录与生成二维码均换成本地

**Comment by dudt** [comment]
> [fe19ccf](https://github.com/kukume/tgbot/commit/fe19ccf00f28e65f74e7023dca183f11dc25e24e) 登录与生成二维码均换成本地

谢谢大佬
