### ISSUE TITLE
InternalError

### ISSUE THREAD

**Issue by dudt** [kukume/tgbot#8]
![image](https://github.com/kukume/tgbot/assets/19968269/b281d0f3-9dcc-4a69-abd6-a27931aa89c0)
这是啥情况啊？

**Comment by kukume** [comment]
这是阿里云盘接口返回的。
第一个不明白，忘记把message打出来了。
第二个应该是任务没完成。

**Comment by kukume** [comment]
尝试手动执行一下。

**Comment by kukume** [comment]
如果依然失败，更新一下
502d297
可以显示返回的错误信息了

**Comment by dudt** [comment]
感谢大佬！反应迅速
